# Setup
title:               Figmenta.
tagline:             ''
description:         'La ficción sigue viva.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Roberto Sesarego
  url:
  email:             rsesarego@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
